### ISSUE TITLE
Thanks + DefinitelyTyped

### ISSUE THREAD

**Issue by kenhowardpdx** [mvidailhet/ngcordova-typescript-definitions#1]
Thanks for writing this definition. Will you be submitting this to [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped)?

**Comment by mvidailhet** [comment]
Hi @kenhowardpdx ! That's a great idea. I actually haven't written all the definitions yet, but I'm sure it can be accepted as is.

**Comment by smajl** [comment]
Wow, can't wait to see this submitted to official repo! Please do it ASAP :)

**Comment by kenhowardpdx** [comment]
@mvidailhet It may make sense to modularize the definitions. Maybe have one `ngcordova.d.ts` that covers all the global definitions and then separate definition files for each cordova plugin. That way you can focus on the global definitions and anyone that needs a plugin definition that doesn't exist can write their own. I only need the date picker definition presently so your definition file works. You can ignore this if you want :)

**Comment by Zorgatone** [comment]
@mvidailhet please review this: https://github.com/borisyankov/DefinitelyTyped/pull/6513
